lab3/MiSite1/my_apps/carSale/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from MiSite1 import settings
from . import views
from django.conf.urls import url

urlpatterns = [
     path('', views.AutoListView.as_view(), name='Home'),
     path('<int:pk>/', views.AutoDetailView.as_view(), name='car-detail'),
     path('register/', views.RegisterFormView.as_view(), name='register'),
     path('login/', views.user_login, name='login'),
     path('logout/', views.user_logout, name='logout'),
     path('newCar/', views.new_car, name='newCar'),


]

lab3/MiSite1/my_apps/carSale/models.py
from django.db import models
from django.forms import ModelForm
from django.urls import reverse


class Company(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class EngineType(models.Model):
    types = (('Бензин', 'Бензин'), ('Дизель', 'Дизель'), ('Электро', 'Электро'), ('None', 'None'))
    engine_type = models.CharField(max_length=20, choices=types, blank=True, default='N')

    def __str__(self):
        return self.engine_type


class BodyType(models.Model):
    types = (
        ('Седан', 'Седан'), ('Универсал', 'Универсал'), ('Внедорожник', 'Внедорожник'), ('Кроссовер', 'Кроссовер'),
        ('Хэтчбэк', 'Хэтчбэк'), ('None', 'None'))
    body_type = models.CharField(max_length=20, choices=types, blank=True, default='N')

    def __str__(self):
        return self.body_type


class Car(models.Model):
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)
    name_model = models.CharField(max_length=30, null=True)
    engine = models.ForeignKey(EngineType, on_delete=models.CASCADE, null=True)
    body = models.ForeignKey(BodyType, on_delete=models.CASCADE, null=True)
    description = models.TextField(null=True)
    img = models.ImageField(upload_to='images/', null=True, blank=True)
    price = models.IntegerField(null=True)

    def __str__(self):
        return self.name_model

    def get_absolute_url(self):
        return reverse('car-detail', args=[str(self.id)])

lab3/MiSite1/my_apps/carSale/forms.py
from django import forms
from django.forms import ModelForm

from my_apps.carSale.models import Car


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ('company', 'name_model', 'engine', 'body', 'description', 'img', 'price',)

lab3/MiSite1/my_apps/carSale/views.py
from django.contrib.auth import authenticate, login
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic import FormView
from .forms import LoginForm, CarForm
from .models import Car


class AutoListView(generic.ListView):
    model = Car
    template_name = 'carSale/Home.html'


class AutoDetailView(generic.DetailView):
    model = Car
    template_name = 'carSale/DetailCarInfo.html'


class RegisterFormView(FormView):
    form_class = UserCreationForm
    template_name = 'carSale/register.html'
    success_url = ''

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

    def form_invalid(self, form):
        return super(RegisterFormView, self).form_invalid(form)


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('Home')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'carSale/login.html', {'form': form})


def user_logout(request):
    auth.logout(request)
    return redirect('Home')


def new_car(request):
    car_form = CarForm()
    if request.method == 'POST':
        car_form = CarForm(request.POST, request.FILES)
        if car_form.is_valid():
            car_form.save()
        return redirect('Home')
    return render(request, 'carSale/newCar.html', {'car_form': car_form})

lab3/MiSite1/templates/carSale/DetailCarInfo.html
{% extends "carSale/wrapper.html" %}


{% block content %}
    <style>
        figure {
            width: 100%; /* Ширина */
            float: left; /* Выстраиваем элементы по горизонтали */
            margin: 0 0 0 3.5%; /* Отступ слева */
            background: #f0f0f0; /* Цвет фона */
            border-radius: 5px; /* Радиус скругления */
            padding: 2%; /* Поля */
        }

        figure:first-child {
            margin-left: 0; /* Убираем отступ для первого элемента */
        }
    </style>
    {% if car %}
        <div class="container  bg-light" style="border-radius: 5px;">
            <div class="row">
                <div class="row  box-shadow">
                    <div class="col">
                        <ul class="card-body">
                            <h5 class="card-header-tabs">Год:</h5>
                            <h5></h5>
                            <h5 class="card-header-tabs">Пробег:</h5>
                            <h5></h5>
                            <h5 class="card-header-tabs">Кузов:</h5>
                            <h5></h5>
                            <h5 class="card-header-tabs">Двигатель:</h5>
                        </ul>
                    </div>
                    <div class="col">
                        <ul class="card-body">
                            <h5 class="card-header-tabs"> </h5>
                            <h5></h5>
                            <h5 class="card-header-tabs"> </h5>
                            <h5></h5>
                            <h5 class="card-header-tabs"> {{ car.body }}</h5>
                            <h5></h5>
                            <h5 class="card-header-tabs"> {{ car.engine }}</h5>
                        </ul>
                    </div>
                </div>

                <div class="col">
                    {% if car.img %}
                                <figure>
                                    <img class="card-img-top" alt="Thumbnail [100%x225]" style="border-radius: 5px;height: 460px; width: 100%;
                                display:flow-root" src="{{ car.img.url }}">
                                </figure>
                    {% endif %}
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

lab3/MiSite1/templates/carSale/Home.html
{% extends "carSale/wrapper.html" %}


{% block content %}
    <h1 class="col-md-4" xmlns="http://www.w3.org/1999/html">Автомобили</h1>
    {% if car_list %}
        <style>
            figure {
                width: 100%; /* Ширина */
                float: left; /* Выстраиваем элементы по горизонтали */
                margin: 0 0 0 3.5%; /* Отступ слева */
                background: #f0f0f0; /* Цвет фона */
                border-radius: 5px; /* Радиус скругления */
                padding: 2%; /* Поля */
            }

            figure:first-child {
                margin-left: 0; /* Убираем отступ для первого элемента */
            }
        </style>

        {% for car in car_list %}
            {% if car %}
            <div class="album py5 bg-light">
            <div class="container">
                <div class="col bg-light ">
                    <div class="col md-1">
                        <div class="card md-4 box-shadow">
                            {% if car.img %}
                                <figure>
                                    <img class="card-img-top" alt="Thumbnail [100%x225]" style="border-radius: 5px;height: 460px; width: 100%;
                                display:flow-root" src="{{car.img.url}}">
                                </figure>
                            {% endif %}
                            <div class="card-body">
                                <p class="card-text"> {{ car.company.name }} {{ car.name_model }}  </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-sm btn-outline-secondary"><a
                                                href="{% url 'car-detail' car.pk %}">Подробнее</a></button>
                                    </div>
                                    <small class="text-muted">{{car.price}}$</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}

    {% else %}
        <p>There are no cars in DB</p>
    {% endif %}
{% endblock %}